-- Migration 002: Add BPM, MusicKey and Vibe support

-- Modify AudioFiles table to add BPM and MusicKey
ALTER TABLE AudioFiles ADD (
    BPM FLOAT,
    MusicKey VARCHAR2(2)
)
/

-- Add CHECK constraint for MusicKey
ALTER TABLE AudioFiles ADD CONSTRAINT ck_MusicKey 
    CHECK (MusicKey IN ('A', 'A#', 'B', 'C', 'C#', 'D', 'D#', 'E', 'F', 'F#', 'G', 'G#'))
/

-- Create Vibes table for tag management
CREATE TABLE Vibes (
    Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    Name VARCHAR2(100) NOT NULL UNIQUE
)
/

-- Create join table for AudioFiles and Vibes (many-to-many)
CREATE TABLE AudioFilesVibes (
    AudioFileId NUMBER NOT NULL,
    VibeId NUMBER NOT NULL,
    PRIMARY KEY (AudioFileId, VibeId),
    FOREIGN KEY (AudioFileId) REFERENCES AudioFiles(Id) ON DELETE CASCADE,
    FOREIGN KEY (VibeId) REFERENCES Vibes(Id) ON DELETE CASCADE
)
/

-- Insert sample vibes
INSERT INTO Vibes (Name) VALUES ('Sad')
/
INSERT INTO Vibes (Name) VALUES ('Happy')
/
INSERT INTO Vibes (Name) VALUES ('Upbeat')
/
INSERT INTO Vibes (Name) VALUES ('Chill')
/
INSERT INTO Vibes (Name) VALUES ('Dark')
/
INSERT INTO Vibes (Name) VALUES ('Energetic')
/
