-- Create AdminUsers table
CREATE TABLE AdminUsers (
                            Id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                            Username VARCHAR2(100) NOT NULL UNIQUE,
                            PasswordHash VARCHAR2(255) NOT NULL,
                            CreatedAt TIMESTAMP DEFAULT SYSTIMESTAMP NOT NULL
)
/

-- Optional: insert initial admin (hashed password)
-- Replace the hash below with a real BCrypt hash
INSERT INTO AdminUsers (Username, PasswordHash)
VALUES ('admin', '$2a$12$XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX')
/