@SharpPortfolioBackend_HostAddress = {{SharpPortfolioBackend_HostAddress}}
@fileIdentifier = some-guid-here


#POWERSHELL COMMAND
curl.exe -X POST "http://localhost:5023/api/Audio" `
  -F "File=PATHTOWAV;type=audio/wav" `
  -F "Description=This is a test audio file description." `
  -F "BPM=160" `
  -F "MusicKey=C" `
  -F "Vibes=Chill" `
-F "Vibes=Energetic"

### Get Audio Metadata
GET {{SharpPortfolioBackend_HostAddress}}/api/Audio/{{fileIdentifier}}/metadata
Accept: application/json

### Search Audio
# Filters: query, vibes, key, bpm, page, pageSize
GET {{SharpPortfolioBackend_HostAddress}}/api/Audio?query=test&vibes=Chill&bpm=120&page=1&pageSize=10
Accept: application/json

### Update Audio Metadata
PUT {{SharpPortfolioBackend_HostAddress}}/api/Audio/{{fileIdentifier}}
Content-Type: application/json

{
  "description": "Updated description",
  "bpm": 130,
  "musicKey": "A Minor"
}

### Delete Audio
DELETE {{SharpPortfolioBackend_HostAddress}}/api/Audio/{{fileIdentifier}}

### Download Multiple Audio Files (ZIP)
POST {{SharpPortfolioBackend_HostAddress}}/api/Audio/download-multiple
Content-Type: application/json

[
  "{{fileIdentifier}}"
]

### Get Audio File as MP3
GET {{SharpPortfolioBackend_HostAddress}}/api/Audio/{{fileIdentifier}}/mp3

### Get Audio File as WAV
GET {{SharpPortfolioBackend_HostAddress}}/api/Audio/{{fileIdentifier}}/wav